// This file will be auto-generated by the build process
// It will contain the ABI and type definitions for our contracts
export const PAYROLL_CONTRACT_ABI = [
  // Company Management
  {
    inputs: [{ name: 'name', type: 'string' }],
    name: 'registerCompany',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fundTreasury',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ name: 'companyAddress', type: 'address' }],
    name: 'getCompany',
    outputs: [
      { name: 'name', type: 'string' },
      { name: 'balance', type: 'uint256' },
      { name: 'isActive', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  
  // Employee Management
  {
    inputs: [
      { name: 'employee', type: 'tuple', components: [
        { name: 'name', type: 'string' },
        { name: 'wallet', type: 'address' },
        { name: 'salary', type: 'uint256' },
        { name: 'paymentToken', type: 'address' },
      ]}
    ],
    name: 'addEmployee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'employeeId', type: 'uint256' },
      { name: 'updates', type: 'tuple', components: [
        { name: 'name', type: 'string' },
        { name: 'wallet', type: 'address' },
        { name: 'salary', type: 'uint256' },
        { name: 'isActive', type: 'bool' },
      ]}
    ],
    name: 'updateEmployee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'employeeId', type: 'uint256' }],
    name: 'deactivateEmployee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  
  // Payment Processing
  {
    inputs: [
      { name: 'employeeId', type: 'uint256' },
      { name: 'amount', type: 'uint256' }
    ],
    name: 'processPayment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'employeeIds', type: 'uint256[]' },
      { name: 'amounts', type: 'uint256[]' }
    ],
    name: 'batchProcessPayments',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'amount', type: 'uint256' }],
    name: 'withdrawFromTreasury',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

// Types for the contract methods
export type PayrollContract = {
  // Company Management
  registerCompany: (name: string) => Promise<{ hash: string }>;
  fundTreasury: (value: bigint) => Promise<{ hash: string }>;
  getCompany: (companyAddress: string) => Promise<{
    name: string;
    balance: bigint;
    isActive: boolean;
  }>;
  
  // Employee Management
  addEmployee: (employee: {
    name: string;
    wallet: string;
    salary: bigint;
    paymentToken: string;
  }) => Promise<{ hash: string }>;
  
  updateEmployee: (
    employeeId: bigint,
    updates: {
      name: string;
      wallet: string;
      salary: bigint;
      isActive: boolean;
    }
  ) => Promise<{ hash: string }>;
  
  deactivateEmployee: (employeeId: bigint) => Promise<{ hash: string }>;
  
  // Payment Processing
  processPayment: (employeeId: bigint, amount: bigint) => Promise<{ hash: string }>;
  batchProcessPayments: (employeeIds: bigint[], amounts: bigint[]) => Promise<{ hash: string }>;
  withdrawFromTreasury: (amount: bigint) => Promise<{ hash: string }>;
};
